version: '3'

services:
  mans_leasing:
    build:
      context: .
      dockerfile: docker/mans_leasing/Dockerfile
    hostname: mans_leasing
    container_name: mans_leasing
    environment:
      SERVICE_VARIANT: mans_leasing
      WSGI_NAME: wsgi
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery-worker:
    build:
      context: .
      dockerfile: docker/mans_leasing/Dockerfile
    environment:
      SERVICE_VARIANT: celery-worker
      FIREBASE_FCM_SERVICE_KEY:
    command: /bin/bash -c "celery worker -A config --loglevel ${CELERY_WORKER_LOGLEVEL}"
    env_file:
      - .env
    depends_on:
      - mans_leasing

  db:
    image: bitnami/postgresql:10
    hostname: db
    env_file:
      - .env

  redis:
    image: bitnami/redis:5.0.9
    hostname: redis
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${REDIS_DEFAULT_PASSWORD}

  nginx:
    build:
      context: ./docker/nginx
    command: /bin/bash -c "envsubst '$$PRODUCTION_HOST' < /etc/nginx/nginx.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    env_file:
      - .env
    depends_on:
      - mans_leasing
