# Generated by Django 2.2.4 on 2021-02-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_auto_20210227_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='vypiska_file',
            field=models.FileField(blank=True, null=True, upload_to='lead_files/'),
        ),
    ]
